'use client';
import { useEffect, useMemo, useState } from 'react';
import './dc-product-reference.css';

type Product={name:string;subtitle:string;description:string;tone:string;price:string;pack:string;servings:string;benefits:string[];ingredients:{name:string;role:string;benefit:string;photo?:string}[];groups:{title:string;names:string[];text:string;photos:string[]}[];how:string[];faqs:[string,string][];hero?:string};
const U='https://images.unsplash.com/';
const photos={
 hero:'photo-1685967836529-b0e8d6938227?auto=format&fit=crop&w=1400&q=82',
 oat:'photo-1539279006849-35e5504ce752?auto=format&fit=crop&w=500&q=82',
 peanut:'photo-1574706052773-943579c15a01?auto=format&fit=crop&w=500&q=82',
 banana:'photo-1567789352758-9e3dc54b3ae3?auto=format&fit=crop&w=500&q=82',
 dates:'photo-1769255484739-3437edbb858e?auto=format&fit=crop&w=500&q=82',
 moringa:'photo-1610440042657-612c34d95e9f?auto=format&fit=crop&w=500&q=82'
};
const p=(key:keyof typeof photos)=>U+photos[key];
const baseProducts:Product[]=[
{name:'DC ENERGY',subtitle:'Clean Nutrition for Steady Energy',description:'A balanced blend of plant-based ingredients designed to support your daily energy, nutrition and performance — naturally.',tone:'lime',price:'₹699',pack:'150 g',servings:'Approx. 15 servings',benefits:['Sustained Energy','Plant Nutrition','Everyday Performance'],ingredients:[
{name:'Oat Powder',role:'Everyday fuel',benefit:'Provides natural carbohydrates and fibre.',photo:p('oat')},{name:'Peanut Powder',role:'Plant nutrition',benefit:'Adds plant protein, energy and a rich texture.',photo:p('peanut')},{name:'Banana Powder',role:'Natural energy',benefit:'Adds fruit-derived carbohydrate and flavour.',photo:p('banana')},{name:'Date Powder',role:'Quick energy',benefit:'Adds naturally occurring sugars and sweetness.',photo:p('dates')},{name:'Moringa Powder',role:'Plant goodness',benefit:'Adds a leafy botanical and nutritional variety.',photo:p('moringa')},{name:'Pea Protein',role:'Plant protein',benefit:'Contributes to the protein content of the blend.'},{name:'Rice Protein',role:'Plant protein',benefit:'Adds another plant protein source.'},{name:'Flaxseed Powder',role:'Seed nutrition',benefit:'Contributes fibre and plant-based omega-3 ALA.'},{name:'Cocoa',role:'Cacao flavour',benefit:'Adds chocolate character.'},{name:'Cinnamon',role:'Botanical spice',benefit:'Adds warm aromatic flavour.'},{name:'Natural Vanilla',role:'Natural flavour',benefit:'Rounds out the flavour profile.'}],groups:[
{title:'ENERGY FOUNDATION',names:['Oat','Banana','Dates'],text:'Helps provide sustained energy and natural carbohydrates.',photos:[p('oat'),p('banana'),p('dates')]},
{title:'PLANT PROTEIN',names:['Pea Protein','Rice Protein'],text:'Contributes to your daily protein intake.',photos:[]},
{title:'PLANT NUTRITION',names:['Moringa','Amla','Flaxseed'],text:'Adds natural plant nutrients and fibre.',photos:[p('moringa')]},
{title:'TASTE & BALANCE',names:['Cocoa','Cinnamon','Vanilla'],text:'For a rich, enjoyable taste naturally.',photos:[]}
],how:['Use the recommended amount (see pack for details).','Blend with water, milk or your preferred beverage.','Use as part of your daily routine, anytime you need a natural energy boost.','Best results with regular use as part of a balanced diet and active lifestyle.'],faqs:[['What is DC ENERGY?','A daily plant-based nutrition blend built around whole-food ingredients, plant proteins and botanicals.'],['Who is it for?','For adults looking for a convenient daily nutrition and energy option.'],['How do I use it?','Mix the recommended serving with water, milk or your preferred beverage.'],['What ingredients are inside?','Oat, peanut, banana, dates, pea and rice protein, flaxseed, cocoa, moringa, cinnamon and natural vanilla.'],['Does it contain added sugar?','Check the final product label before making a no-added-sugar claim.'],['How is it different from other energy products?','It is positioned as everyday nutrition rather than a high-stimulant energy drink.']],hero:p('hero')},
{name:'DC WEIGHT GAIN',subtitle:'Plant Nutrition for Easier Weight Gain',description:'A calorie-dense plant-based blend designed to make adding daily nutrition simple and convenient.',tone:'amber',price:'₹699',pack:'150 g',servings:'Approx. 15 servings',benefits:['Calorie Dense','Plant Nutrition','Daily Weight Gain'],ingredients:[],groups:[],how:['Mix the recommended serving with water or milk.','Blend with your preferred additions for a richer shake.','Use consistently alongside a balanced diet.','Adjust total daily intake to your individual nutrition needs.'],faqs:[['What is DC WEIGHT GAIN?','A convenient plant-based nutrition blend designed to add calories and protein to the day.'],['Who is it for?','Adults who want an easier way to add energy and plant nutrition to their routine.'],['How do I use it?','Mix with water or milk and blend until smooth.'],['Is it a meal replacement?','No. It should complement a varied, balanced diet.']],hero:p('hero')},
{name:'DC PLANT PROTEIN',subtitle:'Plant Protein for Everyday Strength',description:'A plant-protein blend pairing pea and rice proteins with creatine for a straightforward daily performance routine.',tone:'lavender',price:'₹699',pack:'150 g',servings:'Approx. 7 servings',benefits:['Plant Protein','3 g Creatine*','Everyday Performance'],ingredients:[{name:'Pea Protein Isolate',role:'Primary plant protein',benefit:'Concentrated plant protein source.'},{name:'Rice Protein Isolate',role:'Complementary plant protein',benefit:'Complements the pea protein source.'},{name:'Creatine Monohydrate',role:'Performance ingredient',benefit:'Formulation is designed around 3 g per 20 g serving.'}],groups:[{title:'PLANT PROTEIN',names:['Pea Protein Isolate','Rice Protein Isolate'],text:'Two concentrated plant protein sources form the core of the formula.',photos:[]},{title:'PERFORMANCE',names:['Creatine Monohydrate'],text:'Creatine is the performance-focused ingredient.',photos:[]}],how:['Mix one 20 g serving with water or milk.','Shake or blend until smooth.','Use consistently as part of your protein and training routine.','Follow the product label and your overall nutrition plan.'],faqs:[['How much creatine is in a serving?','The DC formulation is designed around 3 g creatine monohydrate per 20 g serving.'],['What is the protein source?','Pea protein isolate and rice protein isolate form the protein base.'],['How do I use it?','Mix one 20 g serving with water or milk.']],hero:'/plant-protein-banner.PNG'},
{name:'DC PRE-WORKOUT',subtitle:'Fuel for What’s Next',description:'A focused pre-training formula designed to fit into a simple, repeatable workout ritual.',tone:'coral',price:'₹699',pack:'150 g',servings:'As labelled',benefits:['Workout Readiness','Performance Fuel','Pre-Training'],ingredients:[{name:'Caffeine',role:'Performance stimulant',benefit:'Can increase alertness and reduce perceived effort during exercise.'},{name:'Beetroot',role:'Nitrate-rich botanical',benefit:'Provides naturally occurring dietary nitrates.'},{name:'Citrulline',role:'Amino acid',benefit:'Used in sports nutrition formulas for exercise performance pathways.'},{name:'Beta-Alanine',role:'Performance amino acid',benefit:'Supports muscle carnosine levels with regular use.'}],groups:[{title:'STIMULATION',names:['Caffeine'],text:'A stimulant ingredient used to support alertness and exercise readiness.',photos:[]},{title:'PERFORMANCE PATHWAYS',names:['Beetroot','Citrulline','Beta-Alanine'],text:'Ingredients commonly used in sports-nutrition formulas.',photos:[]}],how:['Mix the recommended serving with water.','Take before training according to the product label.','Do not stack with excessive additional caffeine sources.','Follow the labelled serving size.'],faqs:[['What is DC PRE?','A pre-training formula designed for a focused workout ritual.'],['When should I take it?','Use it before training according to the final product label.'],['Does it contain caffeine?','Yes, the formula includes caffeine.']],hero:p('hero')},
{name:'DC HYDRATION',subtitle:'Electrolytes for Everyday Life',description:'A simple daily hydration blend designed to make staying hydrated more convenient.',tone:'blue',price:'₹699',pack:'150 g',servings:'As labelled',benefits:['Daily Hydration','Electrolytes','Everyday Life'],ingredients:[{name:'Electrolyte Minerals',role:'Hydration support',benefit:'Provide minerals involved in fluid and electrolyte balance.'}],groups:[{title:'HYDRATION SUPPORT',names:['Electrolyte Minerals'],text:'Minerals involved in normal fluid and electrolyte balance.',photos:[]}],how:['Mix the recommended serving into water.','Shake or stir until fully dispersed.','Sip throughout your normal day or around activity.','Use according to the product label and your individual hydration needs.'],faqs:[['What is DC HYDRATION?','A daily hydration blend designed to make staying hydrated more convenient.'],['Can I use it every day?','Use it according to the product label and your individual hydration needs.'],['Is it a replacement for water?','No. It complements normal water intake.']],hero:p('hero')}
];
function Pouch({product}:{product:Product}){return <div className={`ref2-pouch ${product.tone}`}><span>DC<sup>®</sup></span><strong>{product.name.replace('DC ','')}</strong><small>{product.subtitle}</small><em>YOUR DAILY FLEX</em><b>NET WT. 150 g</b></div>}
export default function DCProductDetailsReference(){const[product,setProduct]=useState<Product|null>(null);const[ingredient,setIngredient]=useState(0);const[faq,setFaq]=useState<number|null>(null);const[qty,setQty]=useState(1);const[media,setMedia]=useState(0);const mediaItems=[p('hero'),p('oat'),p('peanut'),p('banana'),p('dates'),p('moringa')];useEffect(()=>{const fn=(e:Event)=>{const name=(e as CustomEvent<string>).detail;const found=baseProducts.find(x=>x.name===name);if(found){setProduct(found);setIngredient(0);setFaq(null);setQty(1);setMedia(0);document.body.classList.add('dc-detail-open')}};window.addEventListener('dc:open-product',fn);return()=>window.removeEventListener('dc:open-product',fn)},[]);useEffect(()=>{if(!product)return;const k=(e:KeyboardEvent)=>e.key==='Escape'&&close();window.addEventListener('keydown',k);return()=>window.removeEventListener('keydown',k)},[product]);const close=()=>{setProduct(null);document.body.classList.remove('dc-detail-open')};const spotlight=useMemo(()=>product?.ingredients.slice(0,4)||[],[product]);if(!product)return null;const selected=spotlight[ingredient%Math.max(1,spotlight.length)];const related=baseProducts.filter(x=>x.name!==product.name).slice(0,3);const displayedMedia=product.name==='DC PLANT PROTEIN'?product.hero:(media<6?mediaItems[media]:mediaItems[0]);return <div className={`dc-ref2 ${product.tone}`} role="dialog" aria-modal="true">
<header><div className="ref2-brand"><b>DC</b><span>DAILY<br/>CONSUMABLES</span></div><nav><button>Shop</button><button>Our Story</button><button>Ingredients</button><button>Learn</button><button className="active">Your Daily Flex</button></nav><div className="ref2-icons"><button>⌕</button><button>♙</button><button>🛒<sup>0</sup></button></div></header>
<main><div className="ref2-crumb">Home <b>›</b> Shop <b>›</b> <strong>{product.name}</strong></div>
<section className="ref2-hero"><div className="ref2-gallery"><div className="ref2-main-photo">{displayedMedia?<img src={displayedMedia} alt={`${product.name} media ${media+1}`}/>:null}{product.name!=='DC PLANT PROTEIN'&&<div className="ref2-overlay-pouch"><Pouch product={product}/></div>}{media===6&&<button className="ref2-video-play" aria-label="Play product video">▶</button>}</div><div className="ref2-media-tabs" role="tablist" aria-label="Product media"><button className={media===0?'active':''} onClick={()=>setMedia(0)} role="tab">01</button><button className={media===1?'active':''} onClick={()=>setMedia(1)} role="tab">02</button><button className={media===2?'active':''} onClick={()=>setMedia(2)} role="tab">03</button><button className={media===3?'active':''} onClick={()=>setMedia(3)} role="tab">04</button><button className={media===4?'active':''} onClick={()=>setMedia(4)} role="tab">05</button><button className={media===5?'active':''} onClick={()=>setMedia(5)} role="tab">06</button><button className={`video ${media===6?'active':''}`} onClick={()=>setMedia(6)} role="tab">▶ VIDEO</button></div></div>
<div className="ref2-info"><small>DC COLLECTION</small><h1>{product.name}</h1><h2>{product.subtitle}</h2><p>{product.description}</p><div className="ref2-benefits">{product.benefits.map((x,i)=><div key={x}><i>{['ϟ','◐','↗'][i]}</i><b>{x}</b></div>)}</div><div className="ref2-buy"><strong>{product.price}</strong><span>{product.pack} ({product.servings})</span></div><div className="ref2-actions"><div><button onClick={()=>setQty(Math.max(1,qty-1))}>−</button><b>{qty}</b><button onClick={()=>setQty(qty+1)}>+</button></div><button className="cart">Add to Cart</button></div><div className="ref2-trust"><span>◉ Plant-based ingredients</span><span>◉ No artificial preservatives*</span><span>◉ Everyday nutrition</span><span>◉ Made for real life</span></div></div></section>
<section className="ref2-ingredients"><div className="ref2-intro"><h2>Real Ingredients<br/>for Real Energy</h2><p>A thoughtfully selected blend of whole-food ingredients, plant proteins and botanicals to support your active everyday life.</p><button onClick={()=>document.getElementById('inside-ref2')?.scrollIntoView({behavior:'smooth'})}>Explore Ingredients <b>›</b></button></div><div className="ref2-photo-row">{product.ingredients.slice(0,5).map(x=><div key={x.name}>{x.photo?<img src={x.photo} alt={x.name}/>:<div className="ref2-fallback">DC</div>}<b>{x.name.replace(' Powder','')}</b><small>{x.role}</small></div>)}</div></section>
<section className="ref2-inside" id="inside-ref2"><div className="ref2-section-head"><div><h2>What’s Inside {product.name}?</h2><p>Each ingredient has a purpose. Together, they create a balanced formula for your daily flex.</p></div><button>See Full Ingredient List ↓</button></div><div className="ref2-groups">{product.groups.map((g,i)=><article key={g.title}><small>{g.title}</small><div className="ref2-group-photos">{g.photos.length?g.photos.map(src=><img key={src} src={src} alt="Ingredient"/>):<div className="ref2-mini-art">DC</div>}</div><b>{g.names.join(' • ')}</b><p>{g.text}</p></article>)}</div></section>
<section className="ref2-learning"><div className="ref2-spot"><h2>Ingredient Spotlight</h2><p>Tap through to learn how each ingredient supports your daily flex.</p><div className="ref2-spot-card"><button onClick={()=>setIngredient((ingredient-1+spotlight.length)%Math.max(1,spotlight.length))}>‹</button>{selected?.photo?<img src={selected.photo} alt={selected.name}/>:<div className="ref2-large-art">DC</div>}<div><h3>{selected?.name||'Formula ingredient'}</h3><p>{selected?.benefit}</p><span>◉ {selected?.role}</span><span>◉ Why it’s in {product.name}:<small> Forms part of the formula foundation</small></span></div><button onClick={()=>setIngredient((ingredient+1)%Math.max(1,spotlight.length))}>›</button></div></div><div className="ref2-how"><h2>How to Use</h2><p>Simple to add to your daily routine.</p><div>{product.how.map((x,i)=><article key={x}><i>{['⌁','▣','☼','▦'][i]}</i><b>{['1 Serving','Mix','When','Be Consistent'][i]}</b><p>{x}</p></article>)}</div></section>
<section className="ref2-bottom"><div className="ref2-faq"><div className="ref2-section-head"><h2>Frequently Asked Questions</h2><button>View all FAQs →</button></div>{product.faqs.map(([q,a],i)=><div key={q} className="ref2-faq-row"><button onClick={()=>setFaq(faq===i?null:i)}><span>ⓘ {q}</span><b>{faq===i?'−':'+'}</b></button>{faq===i&&<p>{a}</p>}</div>)}</div><div className="ref2-related"><h2>You Might Also Like</h2><div>{related.map(x=><article key={x.name}><div className="ref2-related-image">{x.name==='DC PLANT PROTEIN'?<img src="/plant-protein-banner.PNG" alt={x.name}/>:<Pouch product={x}/>}</div><b>{x.name}</b><small>{x.subtitle}</small><strong>{x.price}</strong><button onClick={()=>{setProduct(x);setMedia(0);setIngredient(0);setFaq(null)}}>View Product</button></article>)}</div></div></section>
</main><button className="ref2-close" onClick={close}>×</button></div>}
