'use client';
import { useEffect, useState } from 'react';

const slides = [
  ['DC | DAILY CONSUMABLES','YOUR DAILY','FLEX.','Whatever your day needs, there’s a DC for that.','SHOP DC','#f4ead9','#dce8b9','ENERGY','DAILY ENERGY • PERFORMANCE'],
  ['DC ENERGY','START','STRONG.','A convenient daily blend for energy and everyday performance.','SHOP ENERGY','#f5e6b9','#e7c889','ENERGY','OATS • BANANA • DATES'],
  ['DC PLANT PROTEIN','FUEL YOUR','DAY.','Plant protein with a simple, everyday approach to performance nutrition.','SHOP PROTEIN','#e6e1ef','#c8d5ad','PLANT PROTEIN','PEA • RICE • CREATINE'],
  ['DC HYDRATION','HYDRATE','YOUR DAY.','A refreshing daily hydration ritual for work, training and travel.','SHOP HYDRATION','#dcecef','#a8d8d6','HYDRATION','COCONUT WATER • ELECTROLYTES'],
  ['DC | DAILY WELLNESS','MAKE IT','DAILY.','Build a routine around the DC products that fit your day.','EXPLORE DC','#f3ddd4','#e5b9a9','DAILY','19 PRODUCTS • ONE SYSTEM'],
] as const;

export default function HeroShowcase(){
 const [active,setActive]=useState(0); const s=slides[active];
 useEffect(()=>{const t=window.setInterval(()=>setActive(v=>(v+1)%slides.length),5500);return()=>window.clearInterval(t)},[]);
 return <>
  <style>{`main > section.hero{visibility:hidden}.dc-showcase{position:absolute;top:122px;left:50%;transform:translateX(-50%);z-index:20}.dc-showcase-inner{position:relative;min-height:555px;overflow:hidden;border-radius:0 0 30px 30px;display:grid;grid-template-columns:42% 58%;transition:background .6s ease}.dc-showcase-copy{padding:72px 30px 72px 55px;display:flex;flex-direction:column;justify-content:center;z-index:3}.dc-showcase h1{font-family:'Space Grotesk',sans-serif;font-size:clamp(56px,6vw,92px);line-height:.84;letter-spacing:-.075em;margin:0}.dc-showcase h1 em{font-style:normal;color:#8eae1c}.dc-showcase-lead{font-size:20px;line-height:1.45;max-width:390px;margin:27px 0}.dc-showcase-art{position:relative;overflow:hidden}.dc-orb{position:absolute;width:430px;height:430px;border-radius:50%;right:-40px;top:55px}.dc-pack{position:absolute;right:18%;bottom:58px;width:170px;height:250px;border-radius:12px 12px 18px 18px;background:#191916;color:#fff;box-shadow:0 24px 40px #2b291d38;padding:16px;transform:rotate(-3deg);z-index:2}.dc-pack-logo{font-family:'Space Grotesk';font-size:28px;font-weight:700;letter-spacing:-.08em}.dc-pack-small{font-size:6px;letter-spacing:.15em;font-weight:700}.dc-pack-name{margin-top:92px;font-family:'Space Grotesk';font-size:23px;line-height:.9;font-weight:700}.dc-pack-note{font-size:7px;margin-top:7px;color:#ddd}.dc-shaker{position:absolute;right:5%;bottom:44px;width:82px;height:190px;border-radius:16px 16px 28px 28px;background:#252520;color:#fff;box-shadow:0 20px 30px #2222;text-align:center;padding-top:18px;font-family:'Space Grotesk';font-size:23px;z-index:3}.dc-shaker span{display:block;font-size:8px;line-height:1.1;margin-top:35px;color:#c7e33a}.dc-scene{position:absolute;left:30px;bottom:34px;width:100px;height:54px;border-radius:0 0 55px 55px;background:#fffdf8;box-shadow:0 12px 25px #493b2518;display:flex;align-items:center;justify-content:center;font-size:12px}.dc-leaf{position:absolute;left:95px;bottom:65px;font-size:54px;color:#78932b;transform:rotate(-25deg)}.dc-strip{position:absolute;bottom:0;left:0;right:0;height:54px;background:#fffdf9dd;backdrop-filter:blur(10px);display:flex;align-items:center;justify-content:space-around;z-index:4;font-size:10px;font-weight:800}.dc-dots{position:absolute;right:25px;top:25px;z-index:5;display:flex;gap:7px}.dc-dots button{height:9px;border:0;border-radius:20px;cursor:pointer}.dc-arrow{position:absolute;top:50%;transform:translateY(-50%);z-index:5;width:38px;height:38px;border-radius:50%;border:1px solid #17171422;background:#fffdf8cc;cursor:pointer;font-size:20px}.dc-prev{left:20px}.dc-next{right:20px}
@media(max-width:760px){main > section.hero{display:none}.dc-showcase{top:122px;width:calc(100% - 24px)}.dc-showcase-inner{min-height:760px;display:block;border-radius:0 0 24px 24px}.dc-showcase-copy{padding:48px 24px 10px}.dc-showcase h1{font-size:60px}.dc-showcase-lead{font-size:17px;margin:20px 0}.dc-showcase-art{height:440px}.dc-orb{width:330px;height:330px;right:-55px;top:20px}.dc-pack{right:19%;bottom:40px;width:145px;height:215px}.dc-pack-name{margin-top:75px;font-size:20px}.dc-shaker{right:4%;bottom:28px;height:160px}.dc-scene{left:10px;bottom:24px}.dc-leaf{left:65px;bottom:55px}.dc-strip{height:48px;font-size:8px}.dc-strip span:nth-child(3){display:none}.dc-arrow{top:43%}}`}</style>
  <section className="wrap dc-showcase" id="top"><div className="dc-showcase-inner" style={{background:s[5]}}>
   <div className="dc-showcase-copy"><p className="eyebrow">{s[0]}</p><h1>{s[1]}<br/><em>{s[2]}</em></h1><p className="dc-showcase-lead">{s[3]}</p><div className="hero-ctas"><a className="btn primary" href="#collection">{s[4]} <span>→</span></a><a className="btn outline" href="#find">FIND MY FLEX <span>✦</span></a></div></div>
   <div className="dc-showcase-art"><div className="dc-orb" style={{background:s[6]}}/><div className="dc-scene">● ● ●</div><div className="dc-leaf">⌁</div><div className="dc-pack"><div className="dc-pack-logo">DC</div><div className="dc-pack-small">DAILY CONSUMABLES</div><div className="dc-pack-name" style={{color:s[7]}}>{s[7]}</div><div className="dc-pack-note">{s[8]}</div><div style={{position:'absolute',bottom:14,left:16,fontSize:6,color:'#aaa'}}>150 G • VEGAN</div></div><div className="dc-shaker">DC<span>YOUR<br/>DAILY<br/>FLEX.</span></div></div>
   <div className="dc-strip"><span>PLANT-BASED</span><span>PURE INGREDIENTS</span><span>NO UNNECESSARY ADDITIVES</span><span>MADE IN INDIA</span></div>
   <div className="dc-dots">{slides.map((_,i)=><button key={i} aria-label={`Slide ${i+1}`} onClick={()=>setActive(i)} style={{width:i===active?34:9,background:i===active?'#171714':'#17171455'}}/>)}</div>
   <button className="dc-arrow dc-prev" aria-label="Previous slide" onClick={()=>setActive((active-1+slides.length)%slides.length)}>‹</button><button className="dc-arrow dc-next" aria-label="Next slide" onClick={()=>setActive((active+1)%slides.length)}>›</button>
  </div></section>
 </>;
}
