'use client'
import { useState } from 'react'
const products=[['DC PLANT PROTEIN','Muscle Building','PROTEIN','₹699'],['DC ENERGY','Natural Energy','ENERGY','₹699'],['DC PRE-WORKOUT','Performance','PRE-WORKOUT','₹699'],['DC HYDRATION','Hydration','HYDRATION','₹699'],['DC BRAIN BOOSTER','Focus & Memory','BRAIN','₹699'],['DC SUGAR CONTROL','Sugar Balance','SUGAR','₹699']]
const uses=[['⚡','FITNESS','Build. Perform.'],['☀','DAILY USE','Everyday nutrition.'],['▣','WEIGHT MANAGEMENT','Your goals.'],['☾','NIGHT RITUAL','Recover. Relax.'],['✦','BEAUTY','Glow inside.'],['♢','IMMUNITY','Stronger every day.'],['♡','HEART HEALTH','Care every day.'],['◌','DIGESTION','Happy gut.'],['🏃','ACTIVE LIFESTYLE','Always ready.']]
const ingredients=['PEA PROTEIN','MORINGA','MACA ROOT','FLAXSEED','OATS','AMLA','BEETROOT','ASHWAGANDHA']
function Pouch({name,type}:{name:string,type:string}){return <div className="pouch"><div className="pouch-logo">DC</div><small>DAILY<br/>CONSUMABLES</small><div className="pouch-name">{type}</div><div className="pouch-line"/><b>{name.replace('DC ','')}</b><div className="pouch-bottom">PURE VEGAN • PLANT BASED</div></div>}
export default function Home(){const [slide,setSlide]=useState(0); const [tab,setTab]=useState('ALL'); const hero=['PURE VEGAN|PROTEIN|WITH CREATINE','NATURAL|ENERGY|THAT LASTS','BRAIN BOOSTER|FOR KIDS &|ADULTS','STAY HYDRATED.|PERFORM|BETTER.','SUGAR CONTROL|NATURALLY','WHOLE BODY|WELLNESS|EVERY DAY','THE COMPLETE|DC RANGE|FOR YOU']; const h=hero[slide].split('|'); return <main>
<div className="top"><span>✦ FREE SHIPPING ON ORDERS ABOVE ₹1499</span><span>✦ 100% PLANT-BASED</span><span>✦ NO CHEMICALS</span><span>✦ NO PRESERVATIVES</span><span>✦ NO COLOURS</span><span>✦ PURE VEGAN</span></div>
<header><a className="logo"><strong>DC</strong><span>DAILY<br/>CONSUMABLES</span></a><nav><a>SHOP⌄</a><a>THE DAILY 5</a><a>FIND YOUR FLEX <i>AI</i></a><a>ABOUT DC</a><a>BLOGS</a><a>REWARDS</a></nav><div className="actions">⌕　♙　🛒<sup>0</sup></div></header>
<section className="hero"><div className="hero-bg" style={{transform:`translateX(-${slide*100}%)`}}>{[0,1,2,3,4,5,6].map(i=><div className="hero-photo" key={i} style={{backgroundImage:`url(https://images.unsplash.com/photo-${['1534438327276-14e5300c3a48','1571019613454-1cb2f99b2d8b','1538805060514-97d9cc17730c','1517836357463-d25dfeac3438','1583454110551-21f7e4a55e8c','1549476464-37392f717541','1532384748853-8f54f5d7a39e'][i]}?auto=format&fit=crop&w=1800&q=85)`}}><div className="overlay"/></div>)}</div><div className="hero-copy"><small>01 / PERFORMANCE</small><h1>{h[0]}<br/>{h[1]}<br/><em>{h[2]}</em></h1><p>Build lean muscle. Get stronger.<br/>Every. Single. Day.</p><div><button>SHOP NOW →</button><button className="ghost">VIEW PRODUCT</button></div></div><button className="arrow l" onClick={()=>setSlide((slide+6)%7)}>‹</button><button className="arrow r" onClick={()=>setSlide((slide+1)%7)}>›</button><div className="dots">{hero.map((_,i)=><button className={i===slide?'on':''} key={i} onClick={()=>setSlide(i)}/>)}</div></section>
<section className="hero-rail">{hero.map((x,i)=><button onClick={()=>setSlide(i)} className={i===slide?'sel':''} key={i}><div className="mini"><span>0{i+1}</span><b>{x.split('|')[0]}</b></div><small>{x.split('|')[1]}<br/><em>{x.split('|')[2]}</em></small></button>)}</section>
<section className="standard"><div><small>OUR STANDARD</small><h2>NO BS.<br/><em>JUST REAL STUFF.</em></h2><p>At DC, we believe your body deserves clean, honest nutrition. No chemicals. No preservatives. No unnecessary fillers. Just purposeful plant-powered formulas made from real ingredients. Nothing more.</p></div><div className="standards">{['◇ NO SUGAR','⌁ NO CHEMICALS','◉ NO COLOURS','♧ NO PRESERVATIVES','◒ PURE VEGAN'].map(x=><div key={x}><span>{x.slice(0,1)}</span><b>{x.slice(2)}</b></div>)}</div></section>
<section className="black-strip"><div>🌱 <b>PLANT-BASED</b><small>Nature is our only source</small></div><div>♧ <b>PURE SUPERFOOD</b><small>Real ingredients.<br/>Real results.</small></div><div>⚗ <b>LAB TESTED</b><small>Every batch.<br/>Every time.</small></div><div>▱ <b>FAST & SAFE DELIVERY</b><small>Pan India.<br/>On time, every time.</small></div></section>
<section className="products"><div className="section-head"><div><small>THE DC COLLECTION</small><h2>OUR <em>PRODUCTS</em></h2><p>19 Powerful Products. Every Day Need.</p></div><button>VIEW ALL PRODUCTS →</button></div><div className="tabs">{['ALL','DAILY','FITNESS','BODY','MIND','SUGAR'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="product-grid">{products.map(p=><div className="product" key={p[0]}><Pouch name={p[0]} type={p[2]}/><b>{p[0]}</b><small>{p[1]}</small><strong>{p[3]} <i>150g</i></strong><span>VIEW PRODUCT →</span></div>)}</div></section>
<section className="use"><div className="section-head"><div><small>FIND YOUR DAILY FLEX</small><h2>MADE FOR <em>EVERY YOU.</em></h2></div></div><div className="use-grid">{uses.map(u=><div key={u[1]}><span>{u[0]}</span><b>{u[1]}</b><small>{u[2]}</small></div>)}</div></section>
<section className="ingredients"><div><small>FROM NATURE</small><h2>REAL INGREDIENTS.<br/><em>REAL NUTRITION.</em></h2><p>We use real, whole-food ingredients packed with natural goodness. No shortcuts. Just nature.</p><button>SEE OUR INGREDIENTS →</button></div><div className="ingredient-grid">{ingredients.map((x,i)=><div key={x}><span>{['🌱','🍃','🥜','◉','🌾','🍏','●','🌿'][i]}</span><b>{x}</b></div>)}</div></section>
<section className="how"><div className="section-head"><div><small>SIMPLE. QUICK. EFFECTIVE.</small><h2>HOW TO <em>USE</em></h2></div></div><div className="how-grid">{[['1','SCOOP','Take 1–2 scoops of DC powder.','🥄'],['2','MIX','Add 250–300ml water or milk.','🥤'],['3','SHAKE','Shake well until smooth.','🫨'],['4','DRINK','Fuel your day. Feel the difference.','💪']].map(x=><div key={x[0]}><strong>{x[0]}</strong><span>{x[3]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></section>
<section className="people"><div><small>DC IN REAL LIFE</small><h2>FUELING REAL PEOPLE.<br/><em>REAL RESULTS.</em></h2><p>@dc.dailyflex</p><button>JOIN THE COMMUNITY →</button></div><div className="people-grid">{['1534438327276-14e5300c3a48','1518611012118-696072aa579a','1538805060514-97d9cc17730c','1517836357463-d25dfeac3438','1526401485004-2aa7b9f8a6c8'].map(x=><img key={x} src={`https://images.unsplash.com/photo-${x}?auto=format&fit=crop&w=600&q=80`}/>)}</div></section>
<section className="final"><div><small>YOUR DAILY FLEX.</small><h2>CLEAN NUTRITION.<br/><em>REAL PERFORMANCE.</em></h2><p>NO SUGAR　•　PURE SUPERFOOD　•　NO CHEMICALS　•　NO COLOURS　•　NO PRESERVATIVES　•　PURE VEGAN</p><button>SHOP THE DC RANGE →</button></div><div className="final-products">{products.slice(0,6).map(p=><Pouch key={p[0]} name={p[0]} type={p[2]}/>)}</div></section>
<footer><div><b>DC</b><small>DAILY CONSUMABLES</small><p>YOUR DAILY FLEX.<br/>Plant-based. Herbal.<br/>No unnecessary BS.</p></div><div><b>SHOP</b><span>All Products</span><span>The Daily 5</span><span>Shop by Goal</span><span>Best Sellers</span></div><div><b>SUPPORT</b><span>FAQ</span><span>Shipping & Delivery</span><span>Returns & Refunds</span><span>Contact Us</span></div><div><b>ABOUT DC</b><span>Our Story</span><span>Ingredient Philosophy</span><span>Blogs</span><span>Rewards</span></div><div><b>STAY UPDATED</b><span>Get exclusive offers.</span><input placeholder="Enter your email"/></div></footer>
</main>}
