'use client'
import {useEffect,useState} from 'react'

const slides=[
 {eyebrow:'01 / PERFORMANCE',title:['PURE VEGAN','PROTEIN WITH'],accent:'CREATINE',body:'Plant-powered protein designed for everyday strength, recovery and performance.',image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=2200&q=90'},
 {eyebrow:'02 / ENERGY',title:['NATURAL ENERGY','THAT KEEPS YOU'],accent:'MOVING.',body:'Clean plant-powered fuel for long days, hard sessions and everything between.',image:'https://images.unsplash.com/photo-1579758629938-03607ccdbaba?auto=format&fit=crop&w=2200&q=90'},
 {eyebrow:'03 / MIND',title:['SHARP MIND.','STRONGER'],accent:'DAY.',body:'Daily nutrition built around focus, clarity and a better routine.',image:'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=2200&q=90'},
 {eyebrow:'04 / HYDRATION',title:['STAY HYDRATED.','PERFORM'],accent:'BETTER.',body:'Refreshing daily hydration for training, travel and active days.',image:'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?auto=format&fit=crop&w=2200&q=90'},
 {eyebrow:'05 / BALANCE',title:['SMART DAILY','SUGAR'],accent:'BALANCE.',body:'A purposeful fibre and botanical blend for a balanced everyday routine.',image:'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=2200&q=90'},
 {eyebrow:'06 / WELLNESS',title:['WHOLE BODY','WELLNESS'],accent:'EVERY DAY.',body:'Simple plant-based nutrition that fits naturally into your daily life.',image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=2200&q=90'},
 {eyebrow:'07 / DC RANGE',title:['THE COMPLETE','DC RANGE'],accent:'FOR YOU.',body:'One daily system. Multiple goals. Find the flex that fits your day.',image:'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=2200&q=90'}
]
const products=[['DC PLANT PROTEIN','Muscle Building','PROTEIN','₹699'],['DC ENERGY','Natural Energy','ENERGY','₹699'],['DC PRE-WORKOUT','Performance','PRE-WORKOUT','₹699'],['DC HYDRATION','Hydration','HYDRATION','₹699'],['DC BRAIN BOOSTER','Focus & Memory','BRAIN','₹699'],['DC SUGAR CONTROL','Sugar Balance','SUGAR','₹699']]
const uses=[['⚡','FITNESS','Build. Perform.'],['☀','DAILY USE','Everyday nutrition.'],['▣','WEIGHT MANAGEMENT','Your goals.'],['☾','NIGHT RITUAL','Recover. Relax.'],['✦','BEAUTY','Glow inside.'],['♢','IMMUNITY','Stronger every day.'],['♡','HEART HEALTH','Care every day.'],['◌','DIGESTION','Happy gut.'],['🏃','ACTIVE LIFESTYLE','Always ready.']]
const ingredients=['PEA PROTEIN','MORINGA','MACA ROOT','FLAXSEED','OATS','AMLA','BEETROOT','ASHWAGANDHA']
const people=['1534438327276-14e5300c3a48','1518611012118-696072aa579a','1538805060514-97d9cc17730c','1517836357463-d25dfeac3438','1526401485004-2aa7b9f8a6c8']
function Pouch({name,type}:{name:string,type:string}){return <div className="pouch"><div className="pouch-logo">DC</div><small>DAILY<br/>CONSUMABLES</small><div className="pouch-name">{type}</div><div className="pouch-line"/><b>{name.replace('DC ','')}</b><div className="pouch-bottom">PURE VEGAN • PLANT BASED</div></div>}
function Header(){return <><div className="top"><span>✦ FREE SHIPPING ON ORDERS ABOVE ₹1499</span><span>✦ 100% PLANT-BASED</span><span>✦ NO CHEMICALS</span><span>✦ NO PRESERVATIVES</span><span>✦ NO COLOURS</span><span>✦ PURE VEGAN</span></div><header><a className="logo"><strong>DC</strong><span>DAILY<br/>CONSUMABLES</span></a><nav><a>SHOP⌄</a><a>THE DAILY 5</a><a>FIND YOUR FLEX <i>AI</i></a><a>ABOUT DC</a><a>BLOGS</a><a>REWARDS</a></nav><div className="actions">⌕　♙　🛒<sup>0</sup></div></header></>}
export default function Home(){const[slide,setSlide]=useState(0);const[tab,setTab]=useState('ALL');useEffect(()=>{const t=setInterval(()=>setSlide(v=>(v+1)%slides.length),6000);return()=>clearInterval(t)},[]);const s=slides[slide];return <main><Header/>
<section className="hero"><div className="hero-bg" style={{transform:`translateX(-${slide*14.285714}%)`}}>{slides.map((x,i)=><div className="hero-photo" key={i} style={{backgroundImage:`url(${x.image})`}}><div className="overlay"/></div>)}</div><div className="hero-copy"><small>{s.eyebrow}</small><h1>{s.title[0]}<br/>{s.title[1]}<br/><em>{s.accent}</em></h1><p>{s.body}</p><div><button>SHOP THE COLLECTION →</button><button className="ghost">FIND YOUR FLEX</button></div></div><button className="arrow l" onClick={()=>setSlide((slide+slides.length-1)%slides.length)}>‹</button><button className="arrow r" onClick={()=>setSlide((slide+1)%slides.length)}>›</button><div className="dots">{slides.map((_,i)=><button className={i===slide?'on':''} key={i}/>)}</div></section>
<section className="hero-rail">{[
 ['01','PURE VEGAN','PROTEIN','WITH CREATINE',0],['02','NATURAL','ENERGY','THAT LASTS',1],['03','BRAIN BOOSTER','FOR KIDS &','ADULTS',2],['04','STAY HYDRATED','PERFORM','BETTER',3],['05','SUGAR CONTROL','NATURALLY','','4'],['06','WHOLE BODY','WELLNESS','EVERY DAY',5],['07','THE COMPLETE','DC RANGE','FOR YOU',6]
 ].map(x=><button key={x[0]} className={slide===Number(x[4])?'sel':''} onClick={()=>setSlide(Number(x[4]))}><div className="mini" style={{backgroundImage:`url(${slides[Number(x[4])].image})`}}><span>{x[0]}</span><b>{x[1]}</b></div><small><em>{x[2]}</em><br/>{x[3]}</small></button>)}</section>
<section className="standard"><div><small>OUR STANDARD</small><h2>NO BS. <em>JUST REAL STUFF.</em></h2></div><p>At DC, we believe your body deserves clean, honest nutrition. No unnecessary fillers. Just purposeful plant-powered formulas made from real ingredients. Nothing more.</p><div className="standards">{[['◇','100% PLANT BASED'],['⌁','NO CHEMICALS\nNO PRESERVATIVES'],['◉','CLEAN INGREDIENTS'],['♧','TRUSTED QUALITY'],['◒','REAL RESULTS']].map(x=><div key={x[1]}><span>{x[0]}</span><b>{x[1].split('\n').map((v,i)=><span key={v}>{i>0&&<br/>}{v}</span>)}</b></div>)}</div></section>
<section className="black-strip"><div>🌱 <b>PLANT-BASED</b><small>Nature is our only source</small></div><div>♧ <b>PURE SUPERFOOD</b><small>Real ingredients.<br/>Real results.</small></div><div>⚗ <b>LAB TESTED</b><small>Every batch.<br/>Every time.</small></div><div>▱ <b>FAST & SAFE DELIVERY</b><small>Pan India.<br/>On time, every time.</small></div></section>
<section className="products"><div className="section-head"><div><small>THE DC COLLECTION</small><h2>OUR <em>PRODUCTS</em></h2><p>19 Powerful Products. Every Day Need.</p></div><button>VIEW ALL PRODUCTS →</button></div><div className="tabs">{['ALL','DAILY','FITNESS','BODY','MIND','SUGAR'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div><div className="product-grid">{products.map(p=><div className="product" key={p[0]}><Pouch name={p[0]} type={p[2]}/><b>{p[0]}</b><small>{p[1]}</small><strong>{p[3]} <i>150g</i></strong><span>VIEW PRODUCT →</span></div>)}</div></section>
<section className="use"><div className="section-head"><div><small>FIND YOUR DAILY FLEX</small><h2>MADE FOR <em>EVERY YOU.</em></h2></div></div><div className="use-grid">{uses.map(u=><div key={u[1]}><span>{u[0]}</span><b>{u[1]}</b><small>{u[2]}</small></div>)}</div></section>
<section className="ingredients"><div><small>FROM NATURE</small><h2>REAL INGREDIENTS.<br/><em>REAL NUTRITION.</em></h2><p>We use real, whole-food ingredients packed with natural goodness. No shortcuts. Just nature.</p><button>SEE OUR INGREDIENTS →</button></div><div className="ingredient-grid">{ingredients.map((x,i)=><div key={x}><span>{['🌱','🍃','🥜','◉','🌾','🍏','●','🌿'][i]}</span><b>{x}</b></div>)}</div></section>
<section className="how"><div className="section-head"><div><small>SIMPLE. QUICK. EFFECTIVE.</small><h2>HOW TO <em>USE</em></h2></div></div><div className="how-grid">{[['1','SCOOP','Take 1–2 scoops of DC powder.','🥄'],['2','MIX','Add 250–300ml water or milk.','🥤'],['3','SHAKE','Shake well until smooth.','🫨'],['4','DRINK','Fuel your day. Feel the difference.','💪']].map(x=><div key={x[0]}><strong>{x[0]}</strong><span>{x[3]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}</div></section>
<section className="people"><div><small>DC IN REAL LIFE</small><h2>FUELING REAL PEOPLE.<br/><em>REAL RESULTS.</em></h2><p>@dc.dailyflex</p><button>JOIN THE COMMUNITY →</button></div><div className="people-grid">{people.map(x=><img key={x} src={`https://images.unsplash.com/photo-${x}?auto=format&fit=crop&w=600&q=80`} alt="DC community"/>)}</div></section>
<section className="final"><div><small>YOUR DAILY FLEX.</small><h2>CLEAN NUTRITION.<br/><em>REAL PERFORMANCE.</em></h2><p>NO SUGAR　•　PURE SUPERFOOD　•　NO CHEMICALS　•　NO COLOURS　•　NO PRESERVATIVES　•　PURE VEGAN</p><button>SHOP THE DC RANGE →</button></div><div className="final-products">{products.map(p=><Pouch key={p[0]} name={p[0]} type={p[2]}/>)}</div></section>
<footer><div><b>DC</b><small>DAILY CONSUMABLES</small><p>YOUR DAILY FLEX.<br/>Plant-based. Herbal.<br/>No unnecessary BS.</p></div><div><b>SHOP</b><span>All Products</span><span>The Daily 5</span><span>Shop by Goal</span><span>Best Sellers</span></div><div><b>SUPPORT</b><span>FAQ</span><span>Shipping & Delivery</span><span>Returns & Refunds</span><span>Contact Us</span></div><div><b>ABOUT DC</b><span>Our Story</span><span>Ingredient Philosophy</span><span>Blogs</span><span>Rewards</span></div><div><b>STAY UPDATED</b><span>Get exclusive offers.</span><input placeholder="Enter your email"/></div></footer></main>}
